jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          command: |
            coverage run -m pytest
            coverage report
            coverage xml
          name: Test
      - store_test_results:
          path: coverage.xml
      - codecov/upload:
          file: coverage.xml
orbs:
  python: circleci/python@1.1.0
  codecov: codecov/codecov@1.0.2
version: 2.1
workflows:
  main:
    jobs:
      - build
